services:
  - type: web
    name: trident-risk-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: sql7.freesqldatabase.com
      - key: DB_NAME
        value: sql7812701
      - key: DB_USER
        value: sql7812701
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 3306
      - key: PYTHON_VERSION
        value: 3.11.7
